global:
  registries:
    internal: container.repository.cloudera.com
    default:  container.repository.cloudera.com
  registryCredsSecret: awc-console-registry-creds

taikunSecret: awc-taikun-secrets

dns:
  baseDomain: "a19881.test.cldr.work"
  clusterDomain: "student07.a19881.test.cldr.work"

preInstallCheckSingleConsole:
  enabled: false

externalDns:
  enabled: true
  chartValues:
    provider:
      name: aws
    aws:
      region: us-west-2
      zoneType: private
    extraArgs:
      zone-id-filter: Z03938622CM271M1MBTUB
    policy: upsert-only
    interval: "30s"
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: student07-route53-creds
            key: aws-access-key-id
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: student07-route53-creds
            key: aws-secret-access-key
      - name: AWS_DEFAULT_REGION
        value: "us-west-2"

